--senha = 1
--insert into usr_usuarios(USR_ID, USR_EMAIL, USR_SENHA) values (1, 'eamoraes@gmail.com', '$2a$10$ekNbDxM.aoJ1a.5AxR.6leIamzSMpfasSz.Zmr96F93k2t/eT4nrC');
--insert into TAR_TAREFAS (TAR_ID ,TAR_CONCLUIDA ,TAR_DATA_EXPIRACAO ,TAR_DESCRICAO ,TAR_TITULO, USR_ID) values (1, false,'2012-1-1','Teste Descricao','Teste Titulo', 1);